import type { Level, Unit } from './types';

/**
 * Flexbox Adventure — พาเหล่าฮีโร่ไปยืนบนวงเวทสีเดียวกับตัวเอง ด้วย CSS ของกระดาน (#field)
 * เนื้อหา เรื่องเล่า และลำดับด่านเขียนขึ้นใหม่สำหรับสาขา (ไม่ได้คัดลอกจากเว็บอื่น)
 */

const FLEX = { display: 'flex' };
const WRAP = { display: 'flex', 'flex-wrap': 'wrap' };

const K: Unit = { kind: 'knight' };
const M: Unit = { kind: 'mage' };
const A: Unit = { kind: 'archer' };
const PARTY = [K, M, A];
const ARMY = [K, M, A, K, M, A, K, M, A];

function level(id: number, rest: Omit<Level, 'id' | 'edit' | 'selector' | 'lines'> & Partial<Pick<Level, 'edit' | 'selector' | 'lines'>>): Level {
  return { id, edit: 'container', selector: '#field', lines: 3, ...rest };
}

export const FLEXBOX_LEVELS: Level[] = [
  level(1, {
    title: 'ก้าวแรกของอัศวิน',
    story: 'อัศวินตื่นมาในคุกใต้ดิน วงเวทที่จะพาออกไปอยู่สุดทางขวา',
    lesson: [
      '`justify-content` จัดตำแหน่งลูกตาม **แกนหลัก** (ค่าเริ่มคือแนวนอน ซ้าย → ขวา)',
      '`flex-start` ชิดต้นทาง · `flex-end` ชิดปลายทาง · `center` กึ่งกลาง',
    ],
    units: [K],
    base: FLEX,
    fixed: FLEX,
    solution: { 'justify-content': 'flex-end' },
    hint: 'ลอง justify-content: flex-end;',
  }),
  level(2, {
    title: 'จับมือกันตรงกลาง',
    story: 'นักเวทมาสมทบ ทั้งสองต้องยืนกลางห้องโถงพร้อมกัน',
    lesson: ['`justify-content: center` วางกลุ่มลูกไว้กึ่งกลางของแกนหลัก'],
    units: [K, M],
    base: FLEX,
    fixed: FLEX,
    solution: { 'justify-content': 'center' },
    hint: 'ค่าที่ทำให้อยู่ตรงกลางชื่อเดียวกับคำว่า "กลาง" ในภาษาอังกฤษ',
  }),
  level(3, {
    title: 'ระยะเท่ากันรอบตัว',
    story: 'ครบทีมสามคนแล้ว แต่ละคนต้องมีที่ว่างรอบตัวเท่า ๆ กัน',
    lesson: [
      '`space-around` แบ่งที่ว่างให้ทุกตัวเท่ากันทั้งสองข้าง (ขอบนอกจึงได้ครึ่งเดียว)',
      '`space-evenly` ทำให้ช่องว่างทุกช่อง (รวมขอบ) เท่ากันพอดี',
    ],
    units: PARTY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'justify-content': 'space-around' },
    hint: 'มีคำว่า around',
  }),
  level(4, {
    title: 'ชิดกำแพงสองฝั่ง',
    story: 'คนซ้ายสุดและขวาสุดต้องแนบกำแพง คนกลางยืนกึ่งกลางพอดี',
    lesson: ['`space-between` ตัวแรกชิดต้นทาง ตัวสุดท้ายชิดปลายทาง ที่ว่างที่เหลือแบ่งให้ระหว่างกลาง'],
    units: PARTY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'justify-content': 'space-between' },
    hint: 'ที่ว่างอยู่ "ระหว่าง" ตัวละครเท่านั้น',
  }),
  level(5, {
    title: 'ลงไปชั้นล่าง',
    story: 'บันไดลงอยู่ที่พื้นห้อง ทั้งทีมต้องลงไปยืนด้านล่าง',
    lesson: [
      '`align-items` จัดตำแหน่งตาม **แกนขวาง** (ตั้งฉากกับแกนหลัก ค่าเริ่มคือแนวตั้ง)',
      '`flex-start` บน · `center` กลาง · `flex-end` ล่าง · `baseline` ตามเส้นฐานตัวอักษร',
    ],
    units: PARTY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'align-items': 'flex-end' },
    hint: 'align-items คล้าย justify-content แต่ทำงานแนวตั้ง',
  }),
  level(6, {
    title: 'ใจกลางวิหาร',
    story: 'วงเวทศักดิ์สิทธิ์อยู่กลางวิหารพอดี ทั้งแนวนอนและแนวตั้ง',
    lesson: ['ใช้สองคุณสมบัติพร้อมกันได้ — `justify-content` (แนวนอน) + `align-items` (แนวตั้ง)'],
    units: [K],
    base: FLEX,
    fixed: FLEX,
    solution: { 'justify-content': 'center', 'align-items': 'center' },
    hint: 'ต้องใช้ center สองครั้ง',
  }),
  level(7, {
    title: 'ตั้งแถวที่ท่าเรือ',
    story: 'เรือจอดอยู่ด้านล่าง ทีมต้องยืนห่างกันเท่า ๆ กันบนท่าเรือ',
    lesson: ['รวมสิ่งที่เรียนมา: เว้นระยะแนวนอนและจัดแนวตั้งในคราวเดียว'],
    units: PARTY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'justify-content': 'space-around', 'align-items': 'flex-end' },
    hint: 'space-around แนวนอน · flex-end แนวตั้ง',
  }),
  level(8, {
    title: 'กระจกเงากลับด้าน',
    story: 'ห้องกระจกทำให้ลำดับกลับหัว คนที่เดินนำต้องไปอยู่หลังสุด',
    lesson: [
      '`flex-direction` เปลี่ยนทิศของแกนหลัก',
      '`row` ซ้าย→ขวา · `row-reverse` ขวา→ซ้าย · `column` บน→ล่าง · `column-reverse` ล่าง→บน',
    ],
    units: PARTY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'flex-direction': 'row-reverse' },
    hint: 'แถวเดิมแต่กลับด้าน',
  }),
  level(9, {
    title: 'บันไดแนวดิ่ง',
    story: 'ทางเดินแคบจนต้องต่อแถวจากบนลงล่าง',
    lesson: ['`flex-direction: column` ทำให้ลูกเรียงเป็นแนวตั้ง แกนหลักกลายเป็นแนวตั้ง'],
    units: PARTY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'flex-direction': 'column' },
    hint: 'คอลัมน์ = แนวตั้ง',
  }),
  level(10, {
    title: 'กลับด้านแล้วชิดไหน',
    story: 'กลับลำดับแล้ว ทีมต้องไปรวมกันฝั่งซ้าย',
    lesson: [
      'เมื่อกลับทิศ ต้นทางกับปลายทางก็สลับกันด้วย — ใน `row-reverse` ค่า `flex-end` คือ **ฝั่งซ้าย**',
    ],
    units: PARTY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'flex-direction': 'row-reverse', 'justify-content': 'flex-end' },
    hint: 'row-reverse + flex-end',
  }),
  level(11, {
    title: 'ตกลงก้นบ่อ',
    story: 'บ่อน้ำลึก ทีมต้องต่อแถวแนวตั้งที่ก้นบ่อ',
    lesson: ['ใน `column` แกนหลักเป็นแนวตั้ง `justify-content: flex-end` จึงดันลงล่าง'],
    units: PARTY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'flex-direction': 'column', 'justify-content': 'flex-end' },
    hint: 'column แล้ว justify-content ชิดปลาย',
  }),
  level(12, {
    title: 'หอคอยกลับหัว',
    story: 'ปีนหอคอยจากล่างขึ้นบน คนแรกอยู่ล่างสุด ทุกคนกระจายเต็มความสูง',
    lesson: ['`column-reverse` เรียงจากล่างขึ้นบน · `space-between` กระจายเต็มแกน'],
    units: PARTY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'flex-direction': 'column-reverse', 'justify-content': 'space-between' },
    hint: 'column-reverse + space-between',
  }),
  level(13, {
    title: 'ด่านทดสอบสามชั้น',
    story: 'กลับลำดับ ยืนกลางห้อง และชิดพื้น — ประตูถึงจะเปิด',
    lesson: ['สามคุณสมบัติพร้อมกัน: ทิศ · แกนหลัก · แกนขวาง'],
    units: PARTY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'flex-direction': 'row-reverse', 'justify-content': 'center', 'align-items': 'flex-end' },
    hint: 'row-reverse · center · flex-end',
  }),
  level(14, {
    title: 'นักเวทขอไปท้ายแถว',
    story: 'นักเวทร่ายคาถาช้า ขอเดินรั้งท้าย — แก้เฉพาะนักเวท',
    lesson: [
      '`order` เปลี่ยนลำดับของลูก**ทีละตัว** (ค่าเริ่ม 0 · มากกว่าไปทีหลัง · ติดลบมาก่อน)',
      'ด่านนี้แก้ CSS ของ `.mage` ไม่ใช่ของกระดาน',
    ],
    edit: 'unit',
    selector: '.mage',
    targetKind: 'mage',
    units: PARTY,
    base: FLEX,
    solution: { order: '1' },
    lines: 2,
    hint: 'order ที่มากกว่า 0',
  }),
  level(15, {
    title: 'นักธนูหมอบต่ำ',
    story: 'ศัตรูยิงมาจากด้านบน นักธนูคนเดียวต้องหมอบลงพื้น',
    lesson: ['`align-self` ใช้กับลูกตัวเดียว ทับค่า `align-items` ของกระดาน'],
    edit: 'unit',
    selector: '.archer',
    targetKind: 'archer',
    units: PARTY,
    base: FLEX,
    solution: { 'align-self': 'flex-end' },
    lines: 2,
    hint: 'align-self: flex-end;',
  }),
  level(16, {
    title: 'อัศวินคุ้มกันท้าย',
    story: 'อัศวินต้องไปท้ายแถวและยืนต่ำคุ้มกันทีม',
    lesson: ['ใช้ `order` และ `align-self` กับตัวละครตัวเดียวพร้อมกันได้'],
    edit: 'unit',
    selector: '.knight',
    targetKind: 'knight',
    units: PARTY,
    base: FLEX,
    solution: { order: '1', 'align-self': 'flex-end' },
    lines: 3,
    hint: 'order: 1; align-self: flex-end;',
  }),
  level(17, {
    title: 'กองทัพล้นแถว',
    story: 'ทหารเก้านายยืนแถวเดียวไม่พอ ต้องขึ้นบรรทัดใหม่',
    lesson: [
      'ค่าเริ่ม `flex-wrap: nowrap` บีบทุกตัวให้อยู่บรรทัดเดียว',
      '`flex-wrap: wrap` ให้ขึ้นบรรทัดใหม่เมื่อไม่พอ · `wrap-reverse` ขึ้นบรรทัดในทิศกลับกัน',
    ],
    units: ARMY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'flex-wrap': 'wrap' },
    hint: 'flex-wrap: wrap;',
  }),
  level(18, {
    title: 'ขบวนแนวตั้งหลายแถว',
    story: 'เดินเป็นคอลัมน์ และแตกเป็นหลายคอลัมน์เมื่อสูงไม่พอ',
    lesson: ['`flex-direction: column` + `flex-wrap: wrap` ทำให้ล้นไปคอลัมน์ถัดไป'],
    units: ARMY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'flex-direction': 'column', 'flex-wrap': 'wrap' },
    hint: 'column + wrap',
  }),
  level(19, {
    title: 'คาถาย่อ flex-flow',
    story: 'นักเวทสอนคาถาย่อ: เขียนบรรทัดเดียวได้ผลเท่าสองบรรทัด',
    lesson: ['`flex-flow: <direction> <wrap>` คือ flex-direction กับ flex-wrap ในบรรทัดเดียว เช่น `flex-flow: row wrap`'],
    units: ARMY,
    base: FLEX,
    fixed: FLEX,
    solution: { 'flex-flow': 'column wrap' },
    lines: 2,
    hint: 'flex-flow: column wrap;',
  }),
  level(20, {
    title: 'รวมแถวไว้ด้านบน',
    story: 'มีหลายแถวแล้ว ทุกแถวต้องอัดกันอยู่ด้านบนของห้อง',
    lesson: [
      '`align-content` จัดตำแหน่ง **ทั้งแถว** เมื่อมีหลายบรรทัด (ต่างจาก align-items ที่จัดภายในแถว)',
      'ค่าที่ใช้ได้: `flex-start` `flex-end` `center` `space-between` `space-around` `stretch`',
    ],
    units: ARMY,
    base: WRAP,
    fixed: WRAP,
    solution: { 'align-content': 'flex-start' },
    hint: 'align-content: flex-start;',
  }),
  level(21, {
    title: 'ลงไปยืนท้ายห้อง',
    story: 'แถวทั้งหมดต้องไปอยู่ด้านล่างของห้อง',
    lesson: ['`align-content: flex-end` ดันทุกแถวลงด้านล่าง'],
    units: ARMY,
    base: WRAP,
    fixed: WRAP,
    solution: { 'align-content': 'flex-end' },
    hint: 'align-content ชิดปลาย',
  }),
  level(22, {
    title: 'หอคอยกลางทะเลสาบ',
    story: 'ขบวนแนวตั้งที่ขึ้นจากล่าง ต้องรวมกลุ่มอยู่กลางห้อง',
    lesson: ['เมื่อแกนหลักเป็นแนวตั้ง `align-content` จะจัดคอลัมน์ในแนวนอนแทน'],
    units: ARMY,
    base: WRAP,
    fixed: WRAP,
    solution: { 'flex-direction': 'column-reverse', 'align-content': 'center' },
    hint: 'column-reverse + align-content: center',
  }),
  level(23, {
    title: 'เว้นช่องหายใจ',
    story: 'ทีมยืนเบียดกันเกินไป ต้องเว้นช่องห่างระหว่างกัน 32px',
    lesson: ['`gap` กำหนดช่องว่างระหว่างลูก (ไม่เพิ่มที่ขอบนอก) · `row-gap` / `column-gap` แยกแนวได้'],
    units: PARTY,
    base: { display: 'flex', 'justify-content': 'center' },
    fixed: { display: 'flex', 'justify-content': 'center' },
    solution: { gap: '32px' },
    lines: 2,
    hint: 'gap: 32px;',
  }),
  level(24, {
    title: 'บอสใหญ่: ประตูแห่ง Flexbox',
    story: 'ด่านสุดท้าย! ใช้ทุกคาถาที่เรียนมาเพื่อเปิดประตูบอส',
    lesson: ['ทิศย้อนกลับทั้งแกนหลักและการขึ้นบรรทัด แล้วจัดทั้งสองแกน — ลองทีละคุณสมบัติแล้วดูว่าตัวละครขยับยังไง'],
    units: ARMY,
    base: FLEX,
    fixed: FLEX,
    solution: {
      'flex-direction': 'column-reverse',
      'flex-wrap': 'wrap-reverse',
      'justify-content': 'center',
      'align-content': 'space-between',
    },
    lines: 5,
    hint: 'column-reverse · wrap-reverse · center · space-between',
  }),
];
