/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SsoController_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SsoController_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SsoController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/player-ratings/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArenaProfileController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProblemsController_getProblems"];
        put?: never;
        post: operations["ProblemsController_createProblem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/manage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProblemsController_getProblemsForManagement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProblemsController_getProblemById"];
        put?: never;
        post?: never;
        delete: operations["ProblemsController_deleteProblem"];
        options?: never;
        head?: never;
        patch: operations["ProblemsController_updateProblem"];
        trace?: never;
    };
    "/api/v1/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SubmissionsController_getSubmissions"];
        put?: never;
        post: operations["SubmissionsController_createSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TestCasesController_createTestCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/problem/{problemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestCasesController_getTestCasesByProblem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["TestCasesController_deleteTestCase"];
        options?: never;
        head?: never;
        patch: operations["TestCasesController_updateTestCase"];
        trace?: never;
    };
    "/api/v1/matches/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MatchesController_joinQueue"];
        delete: operations["MatchesController_leaveQueue"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MatchesController_getCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{matchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MatchesController_getMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{matchId}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MatchesController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{matchId}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MatchesController_markReady"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LanguagesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/code-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CodeRunsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/level-clears": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LevelClearsController_list"];
        put?: never;
        post: operations["LevelClearsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto: {
            status: string;
            service: string;
        };
        SessionDto: {
            /** Format: date-time */
            expiresAt: string | null;
        };
        MeDto: {
            id: string;
            email: string;
            /** @enum {string} */
            coreRole: "student" | "lecturer";
            /** @enum {string} */
            subsystemRole: "STUDENT" | "STAFF";
            session: components["schemas"]["SessionDto"];
        };
        LeaderboardEntryDto: {
            rank: number;
            displayName: string;
            eloRating: number;
        };
        RatingDto: {
            displayName: string;
            eloRating: number;
        };
        ProblemDto: {
            id: string;
            title: string;
            description: string;
            timeLimitMs: number;
        };
        CreateProblemDto: {
            title: string;
            description: string;
            timeLimitMs: number;
            isActive: boolean;
        };
        TestCountDto: {
            testCases: number;
        };
        ProblemManagementDto: {
            id: string;
            title: string;
            description: string;
            timeLimitMs: number;
            isActive: boolean;
            _count: components["schemas"]["TestCountDto"];
        };
        UpdateProblemDto: {
            title?: string;
            description?: string;
            timeLimitMs?: number;
            isActive?: boolean;
        };
        DeletedDto: {
            id: string;
            /** @enum {boolean} */
            deleted: true;
        };
        ProblemSummaryDto: {
            id: string;
            title: string;
            timeLimitMs: number;
        };
        SubmissionDto: {
            id: string;
            /** @enum {string} */
            status: "PENDING" | "EVALUATING" | "ACCEPTED" | "WRONG_ANSWER" | "TIME_LIMIT_EXCEEDED" | "RUNTIME_ERROR" | "COMPILATION_ERROR";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            evaluatedAt: string | null;
        };
        CreateSubmissionDto: {
            problemId: string;
            sourceCode: string;
        };
        TestCaseDto: {
            id: string;
            problemId: string;
            inputData: string;
            expectedOutput: string;
            isHidden: boolean;
        };
        CreateTestCaseDto: {
            problemId: string;
            inputData: string;
            expectedOutput: string;
            isHidden: boolean;
        };
        UpdateTestCaseDto: {
            inputData?: string;
            expectedOutput?: string;
            isHidden?: boolean;
        };
        QueueStateDto: {
            /** @enum {string} */
            state: "idle" | "waiting" | "matched";
            id?: string;
            position?: number;
        };
        ParticipantDto: {
            id: string;
            displayName: string;
            eloRating: number;
        };
        MatchRoundDto: {
            id: string;
            roundNumber: number;
            /** @enum {string} */
            status: "PENDING" | "ACTIVE" | "WON" | "DRAW";
            winnerId: string | null;
            /** Format: date-time */
            endsAt: string | null;
            problem: components["schemas"]["ProblemDto"];
            submissions: components["schemas"]["SubmissionDto"][];
        };
        MatchDto: {
            /** @enum {string} */
            state: "matched";
            id: string;
            /** @enum {string} */
            status: "ACTIVE" | "COMPLETED" | "DRAW";
            winnerId: string | null;
            myPlayerId: string;
            playerOne: components["schemas"]["ParticipantDto"];
            playerTwo: components["schemas"]["ParticipantDto"];
            currentRound: number | null;
            rounds: components["schemas"]["MatchRoundDto"][];
        };
        CreateMatchSubmissionDto: {
            problemId: string;
            sourceCode: string;
        };
        LanguageDto: {
            id: string;
            name: string;
            /** @enum {string} */
            category: "popular" | "systems" | "jvm" | "dotnet" | "scripting" | "shell" | "functional" | "lisp" | "logic" | "classic" | "esoteric" | "web" | "data";
            file: string;
            extension: string;
            /** @enum {string} */
            runtime: "sandbox" | "browser";
            compiled: boolean;
            template: string;
            stdin: string;
        };
        CodeRunDto: {
            language: string;
            /** @enum {string} */
            status: "OK" | "COMPILE_ERROR" | "RUNTIME_ERROR" | "TIME_LIMIT_EXCEEDED" | "OUTPUT_LIMIT_EXCEEDED" | "MEMORY_LIMIT_EXCEEDED";
            exitCode: number | null;
            stdout: string;
            stderr: string;
            compileOutput: string;
            timeMs: number;
            truncated?: boolean;
        };
        CreateCodeRunDto: {
            /** @example python */
            language: string;
            code: string;
            stdin?: string;
        };
        LevelClearDto: {
            id: string;
            /** @enum {string} */
            game: "FLEXBOX" | "GRID";
            level: number;
            /** Format: date-time */
            createdAt: string;
        };
        CreateLevelClearDto: {
            /** @enum {string} */
            game: "FLEXBOX" | "GRID";
            level: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["HealthDto"];
                    };
                };
            };
        };
    };
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["MeDto"];
                    };
                };
            };
        };
    };
    SsoController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SsoController_callback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SsoController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LeaderboardEntryDto"][];
                        meta: {
                            total: number;
                            page: number;
                            limit: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    ArenaProfileController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["RatingDto"];
                    };
                };
            };
        };
    };
    ProblemsController_getProblems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProblemSummaryDto"][];
                        meta: {
                            total: number;
                            page: number;
                            limit: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    ProblemsController_createProblem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProblemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProblemDto"];
                    };
                };
            };
        };
    };
    ProblemsController_getProblemsForManagement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProblemManagementDto"][];
                        meta: {
                            total: number;
                            page: number;
                            limit: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    ProblemsController_getProblemById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProblemDto"];
                    };
                };
            };
        };
    };
    ProblemsController_deleteProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedDto"];
                    };
                };
            };
        };
    };
    ProblemsController_updateProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProblemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProblemDto"];
                    };
                };
            };
        };
    };
    SubmissionsController_getSubmissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SubmissionDto"][];
                        meta: {
                            total: number;
                            page: number;
                            limit: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    SubmissionsController_createSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubmissionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SubmissionDto"];
                    };
                };
            };
        };
    };
    TestCasesController_createTestCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTestCaseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["TestCaseDto"];
                    };
                };
            };
        };
    };
    TestCasesController_getTestCasesByProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["TestCaseDto"][];
                        meta: {
                            total: number;
                            page: number;
                            limit: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    TestCasesController_deleteTestCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedDto"];
                    };
                };
            };
        };
    };
    TestCasesController_updateTestCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTestCaseDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["TestCaseDto"];
                    };
                };
            };
        };
    };
    MatchesController_joinQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["QueueStateDto"];
                    };
                };
            };
        };
    };
    MatchesController_leaveQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["QueueStateDto"];
                    };
                };
            };
        };
    };
    MatchesController_getCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["QueueStateDto"];
                    };
                };
            };
        };
    };
    MatchesController_getMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["MatchDto"];
                    };
                };
            };
        };
    };
    MatchesController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMatchSubmissionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SubmissionDto"];
                    };
                };
            };
        };
    };
    MatchesController_markReady: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["MatchDto"];
                    };
                };
            };
        };
    };
    LanguagesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LanguageDto"][];
                        meta: {
                            total: number;
                            page: number;
                            limit: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    CodeRunsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCodeRunDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["CodeRunDto"];
                    };
                };
            };
        };
    };
    LevelClearsController_list: {
        parameters: {
            query?: {
                game?: "FLEXBOX" | "GRID";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LevelClearDto"][];
                        meta: {
                            total: number;
                            page: number;
                            limit: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    LevelClearsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLevelClearDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LevelClearDto"];
                    };
                };
            };
        };
    };
}
